Repository govpf/mes-demarches, pull requests merged in 2025-08, with the labels that each got.

#146 feat: add specs for pf champs
  spec/graphql/dossier_polynesian_spec.rb
  spec/system/administrateurs/lexpol_models_spec.rb
  spec/system/users/polynesian_fields_spec.rb
Labels: enhancement

#139 Feature/bump 2024 11 12 01
  app/components/conditions/ineligibilite_rules_component/ineligibilite_rules_component.html.haml
  app/components/dossiers/notified_toggle_component.rb
  app/components/dossiers/notified_toggle_component/notified_toggle_component.html.haml
  app/components/editable_champ/departements_component.rb
  app/components/editable_champ/regions_component.rb
  app/components/instructeurs/column_filter_value_component.rb
  app/components/procedure/fixed_footer_component/fixed_footer_component.html.fr.yml
  app/components/procedure/groupes_management_component/groupes_management_component.html.haml
  app/components/procedure/instructeurs_menu_component/instructeurs_menu_component.html.haml
  app/components/procedure/instructeurs_options_component/instructeurs_options_component.html.haml
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  app/controllers/instructeurs/procedure_presentation_controller.rb
  app/helpers/application_helper.rb
  app/jobs/image_processor_job.rb
  app/models/column.rb
  app/models/columns/champ_column.rb
  app/models/columns/json_path_column.rb
  app/models/columns/linked_drop_down_column.rb
  app/models/concerns/addressable_column_concern.rb
  app/models/concerns/attachment_image_processor_concern.rb
  app/models/concerns/columns_concern.rb
  app/models/logic/champ_value.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/linked_drop_down_list_type_de_champ.rb
  app/models/types_de_champ/piece_justificative_type_de_champ.rb
  app/models/types_de_champ/titre_identite_type_de_champ.rb
  app/models/types_de_champ/type_de_champ_base.rb
  app/services/api_geo_service.rb
  app/services/dossier_filter_service.rb
  app/services/dossier_projection_service.rb
  app/services/uninterlace_service.rb
  app/views/administrateurs/groupe_instructeurs/_custom_routing_modal.html.haml
  app/views/administrateurs/procedures/annotations.html.haml
  app/views/administrateurs/procedures/champs.html.haml
  app/views/instructeurs/procedures/show.html.haml
  app/views/layouts/all.html.haml
  spec/components/conditions/champs_conditions_component_spec.rb
  spec/components/instructeurs/column_filter_value_component_spec.rb
  spec/controllers/administrateurs/groupe_instructeurs_controller_spec.rb
  spec/controllers/instructeurs/procedure_presentation_controller_spec.rb
  spec/lib/tasks/re_routing_dossiers_spec.rb
  spec/models/concerns/columns_concern_spec.rb
  spec/services/api_geo_service_spec.rb
  spec/services/dossier_filter_service_spec.rb
  spec/services/dossier_projection_service_spec.rb
  spec/system/administrateurs/procedure_ineligibilite_spec.rb
  spec/system/routing/rules_full_scenario_spec.rb
Labels: version upgrade

#157 fix: Modify css, so font change only apply to description field
  app/assets/stylesheets/instructeur.scss
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
Labels: bug

#158 Feature/bump 2024 11 26 01
  app/components/editable_champ/champ_label_content_component.rb
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
  app/controllers/administrateurs/procedures_controller.rb
  app/controllers/administrateurs/services_controller.rb
  app/controllers/concerns/create_avis_concern.rb
  app/controllers/instructeurs/procedures_controller.rb
  app/javascript/controllers/fix_table_border_controller.ts
  app/models/concerns/champs_validate_concern.rb
  app/models/concerns/dossier_champs_concern.rb
  app/models/concerns/procedure_path_concern.rb
  app/models/procedure.rb
  app/models/procedure_revision.rb
  app/tasks/maintenance/fix_avis_experts_procedure_mismatch_task.rb
  app/views/instructeurs/procedures/_header.html.haml
  app/views/instructeurs/procedures/apercu.html.haml
  app/views/layouts/application.html.haml
  app/views/shared/dossiers/_edit.html.haml
  app/views/shared/dossiers/_edit_annotations.html.haml
  config/locales/views/instructeurs/procedures/email_notifications/en.yml
  config/locales/views/instructeurs/procedures/email_notifications/fr.yml
  config/routes.rb
  spec/controllers/experts/avis_controller_spec.rb
  spec/controllers/instructeurs/procedures_controller_spec.rb
  spec/models/concerns/dossier_champs_concern_spec.rb
  spec/models/procedure_spec.rb
  spec/tasks/maintenance/fix_avis_experts_procedure_mismatch_task_spec.rb
Labels: version upgrade
