Repository govpf/mes-demarches, pull requests merged in 2025-07, with the labels that each got.

#122 fix lexpol multiple choice
  app/services/lexpol_fields_service.rb
Labels: bug

#121 feat: improve lexpol integration context and error handling
  app/components/types_de_champ_editor/champ_component.rb
  app/components/types_de_champ_editor/champ_component/champ_component.html.haml
  app/controllers/champs/lexpol_controller.rb
  app/services/api_lexpol.rb
  spec/services/api_lexpol_service_spec.rb
Labels: enhancement

#129 feat: reactivate parcelle & batiment
  app/assets/stylesheets/te_fenua.scss
  app/components/editable_champ/te_fenua_component/te_fenua_component.html.haml
  app/javascript/new_design/champs/te_fenua.js
  app/javascript/new_design/champs/te_fenua_lib.js
  app/models/types_de_champ/te_fenua_type_de_champ.rb
Labels: enhancement

#134 Feature/bump 2024 10 24 01
  app/components/instructeurs/column_filter_component/column_filter_component.html.haml
  app/controllers/email_checker_controller.rb
  app/controllers/instructeurs/groupe_instructeurs_controller.rb
  app/graphql/api/v2/schema.rb
  app/graphql/api/v2/stored_query.rb
  app/graphql/schema.graphql
  app/graphql/types/champ_type.rb
  app/graphql/types/champs/yes_no_champ_type.rb
  app/javascript/controllers/autosave_controller.ts
  app/javascript/controllers/date_input_hint_controller.ts
  app/javascript/controllers/email_input_controller.ts
  app/jobs/helpscout_create_conversation_job.rb
  app/models/filtered_column.rb
  app/models/procedure.rb
  app/models/types_de_champ/yes_no_type_de_champ.rb
  app/tasks/maintenance/clean_header_section_options_task.rb
  app/views/instructeurs/groupe_instructeurs/show.html.haml
  config/i18n-tasks.yml
  config/locales/models/filtered_column/en.yml
  config/locales/models/filtered_column/fr.yml
  config/locales/views/instructeurs/groupe_instructeurs/fr.yml
  spec/controllers/email_checker_controller_spec.rb
  spec/controllers/instructeurs/groupe_instructeurs_controller_spec.rb
  spec/controllers/instructeurs/procedures_controller_spec.rb
  spec/jobs/helpscout_create_conversation_job_spec.rb
  spec/models/champ_spec.rb
  spec/models/champs/checkbox_champ_spec.rb
  spec/models/champs/yes_no_champ_spec.rb
  spec/models/filtered_column_spec.rb
  spec/models/procedure_spec.rb
  spec/support/shared_examples_for_boolean_champs.rb
  spec/tasks/maintenance/clean_header_section_options_task_spec.rb
Labels: version upgrade

#141 fix: link to good releases repository
  app/views/super_admins/release_notes/index.html.haml
  config/locales/links.en.yml
Labels: bug
